image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew assemble
  - command: ./gradlew build

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - ms-kotlin.kotlin
